server:
  port: 9088
spring:
  application:
    name: cart-service
  redis:
    host: 120.78.67.10
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 120.78.67.10

ly:
  jwt:
    pubKeyPath: C:\StudyData\rsa.pub # 公钥地址
